services:
  app:
    image: co2unter-app:latest
    container_name: co2unter-app
    environment:
      - ConnectionStrings__DefaultConnection=Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
      - CarbonEmissionSettings__ApiKey=${CARBON_EMISSION_APIKEY}
      - OpenWeatherMapSettings__ApiKey=${OPEN_WEATHER_MAP_APIKEY}
    ports:
      - "8080:80"
    networks:
      - app-network
  
  postgres:
    image: postgres:15-alpine
    container_name: co2unter-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - app-network

  frontend:
    image: co2unter-frontend:latest
    container_name: co2unter-frontend
    ports:
      - "8081:80"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: co2unter-nginx
    volumes:
      - ./reverseProxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./reverseProxy/ssl/ssl.crt:/etc/nginx/ssl/ssl.crt
      - ./reverseProxy/ssl/ssl.key:/etc/nginx/ssl/ssl.key
      - ./reverseProxy/app.apk:/var/www/html/app.apk
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
