version: '3.8'

services:
  app:
    build:
      context: ./co2unter.API
      dockerfile: Dockerfile
    container_name: co2unter-app
    ports:
      - "8080:80"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: co2unter-nginx
    volumes:
      - ./reverseProxy/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
