services:
  app:
    image: co2unter-app:latest
    container_name: co2unter-app
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "8080:80"
    networks:
      - app-network
  
  postgres:
    image: postgres:15-alpine
    container_name: co2unter-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - app-network

  frontend:
    image: co2unter-frontend:latest
    container_name: co2unter-frontend
    ports:
      - "8081:80"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: co2unter-nginx
    volumes:
      - ./reverseProxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./reverseProxy/app.apk:/var/www/html/app.apk
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
