version: '3.8'

services:
  app:
    image: co2unter-app:latest
    container_name: co2unter-app
    ports:
      - "8080:80"
    networks:
      - app-network

  frontend:
    image: co2unter-frontend:latest
    container_name: co2unter-frontend
    ports:
      - "8081:80"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: co2unter-nginx
    volumes:
      - ./reverseProxy/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
